CREATE SEQUENCE "DOMAIN_EVENT_ENTRY_SEQ" START WITH 1 INCREMENT 50;
CREATE SEQUENCE "ASSOCIATION_VALUE_ENTRY_SEQ" START WITH 1 INCREMENT 50;
CREATE
MEMORY
TABLE "ASSOCIATION_VALUE_ENTRY"
(
    "ID" BIGINT NOT NULL,
    "ASSOCIATION_KEY" VARCHAR(255) NOT NULL,
    "ASSOCIATION_VALUE" VARCHAR(255),
    "SAGA_ID" VARCHAR(255) NOT NULL,
    "SAGA_TYPE" VARCHAR(255)
);
ALTER TABLE "ASSOCIATION_VALUE_ENTRY"
    ADD CONSTRAINT "CONSTRAINT_B" PRIMARY KEY ("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSOCIATION_VALUE_ENTRY;
CREATE INDEX "IDXK45EQNXKGD8HPDN6XIXN8SGFT" ON "ASSOCIATION_VALUE_ENTRY" ("SAGA_TYPE", "ASSOCIATION_KEY", "ASSOCIATION_VALUE");
CREATE INDEX "IDXGV5K1V2MH6FRXUY5C0HGBAU94" ON "ASSOCIATION_VALUE_ENTRY" ("SAGA_ID", "SAGA_TYPE");
CREATE
MEMORY
TABLE "MENU_ENTITY"
(
    "ID" VARCHAR(255) NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL,
    "MENU_VERSION" INTEGER NOT NULL,
    "RESTAURANT_ID" VARCHAR(255)
);
ALTER TABLE "MENU_ENTITY"
    ADD CONSTRAINT "CONSTRAINT_6" PRIMARY KEY ("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENU_ENTITY;
CREATE
MEMORY
TABLE "MENU_ENTITY_MENU_ITEMS"
(
    "MENU_ENTITY_ID" VARCHAR(255) NOT NULL,
    "MENU_ID" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PRICE" DECIMAL(19, 2)
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENU_ENTITY_MENU_ITEMS;
CREATE
MEMORY
TABLE "RESTAURANT_ENTITY"
(
    "ID" VARCHAR(255) NOT NULL,
    "AGGREGATE_VERSION" BIGINT NOT NULL,
    "NAME" VARCHAR(255)
);
ALTER TABLE "RESTAURANT_ENTITY"
    ADD CONSTRAINT "CONSTRAINT_1" PRIMARY KEY ("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESTAURANT_ENTITY;
CREATE
MEMORY
TABLE "RESTAURANT_ENTITY_MENU_ITEMS"
(
    "RESTAURANT_ENTITY_ID" VARCHAR(255) NOT NULL,
    "MENU_ID" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PRICE" DECIMAL(19, 2)
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESTAURANT_ENTITY_MENU_ITEMS;
CREATE
MEMORY
TABLE "RESTAURANTORDER_ENTITY"
(
    "ID" VARCHAR(255) NOT NULL,
    "AGGREGATE_VERSION" BIGINT NOT NULL,
    "CUSTOMER" VARCHAR(255),
    "RESTAURANT_ID" VARCHAR(255),
    "STATE" VARCHAR(255)
);
ALTER TABLE "RESTAURANTORDER_ENTITY"
    ADD CONSTRAINT "CONSTRAINT_3" PRIMARY KEY ("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESTAURANTORDER_ENTITY;
CREATE
MEMORY
TABLE "RESTAURANTORDER_ENTITY_LINE_ITEMS"
(
    "RESTAURANTORDER_ENTITY_ID" VARCHAR(255) NOT NULL,
    "MENU_ID" VARCHAR(255),
    "NAME" VARCHAR(255),
    "QUANTITY" INTEGER NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESTAURANTORDER_ENTITY_LINE_ITEMS;
CREATE
MEMORY
TABLE "SAGA_ENTRY"
(
    "SAGA_ID" VARCHAR(255) NOT NULL,
    "REVISION" VARCHAR(255),
    "SAGA_TYPE" VARCHAR(255),
    "SERIALIZED_SAGA" BLOB
);
ALTER TABLE "SAGA_ENTRY"
    ADD CONSTRAINT "CONSTRAINT_BD" PRIMARY KEY ("SAGA_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_ENTRY;
CREATE
MEMORY
TABLE "TOKEN_ENTRY"
(
    "PROCESSOR_NAME" VARCHAR(255) NOT NULL,
    "SEGMENT" INTEGER NOT NULL,
    "OWNER" VARCHAR(255),
    "TIMESTAMP" VARCHAR(255) NOT NULL,
    "TOKEN" BLOB,
    "TOKEN_TYPE" VARCHAR(255)
);
ALTER TABLE "TOKEN_ENTRY"
    ADD CONSTRAINT "CONSTRAINT_7" PRIMARY KEY ("PROCESSOR_NAME", "SEGMENT");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TOKEN_ENTRY;
ALTER TABLE "RESTAURANT_ENTITY_MENU_ITEMS"
    ADD CONSTRAINT "FKTFXMWMSRE3LV2H8OT29YQ510N" FOREIGN KEY ("RESTAURANT_ENTITY_ID") REFERENCES "RESTAURANT_ENTITY" ("ID") NOCHECK;
ALTER TABLE "MENU_ENTITY_MENU_ITEMS"
    ADD CONSTRAINT "FKH3K81M5EJHJ6QHEDY1K3QAYTK" FOREIGN KEY ("MENU_ENTITY_ID") REFERENCES "MENU_ENTITY" ("ID") NOCHECK;
ALTER TABLE "RESTAURANTORDER_ENTITY_LINE_ITEMS"
    ADD CONSTRAINT "FKHL5IB1APFX55H61JE9SQIPFGD" FOREIGN KEY ("RESTAURANTORDER_ENTITY_ID") REFERENCES "RESTAURANTORDER_ENTITY" ("ID") NOCHECK;


CREATE
MEMORY
TABLE "DEAD_LETTER_ENTRY"
(
    "DEAD_LETTER_ID" CHARACTER VARYING(255) NOT NULL,
    "CAUSE_MESSAGE" CHARACTER VARYING(255),
    "CAUSE_TYPE" CHARACTER VARYING(255),
    "DIAGNOSTICS" BINARY LARGE OBJECT,
    "ENQUEUED_AT" TIMESTAMP NOT NULL,
    "LAST_TOUCHED" TIMESTAMP,
    "AGGREGATE_IDENTIFIER" CHARACTER VARYING(255),
    "EVENT_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "MESSAGE_TYPE" CHARACTER VARYING(255) NOT NULL,
    "META_DATA" BINARY LARGE OBJECT,
    "PAYLOAD" BINARY LARGE OBJECT NOT NULL,
    "PAYLOAD_REVISION" CHARACTER VARYING(255),
    "PAYLOAD_TYPE" CHARACTER VARYING(255) NOT NULL,
    "SEQUENCE_NUMBER" BIGINT,
    "TIME_STAMP" CHARACTER VARYING(255) NOT NULL,
    "TOKEN" BINARY LARGE OBJECT,
    "TOKEN_TYPE" CHARACTER VARYING(255),
    "TYPE" CHARACTER VARYING(255),
    "PROCESSING_GROUP" CHARACTER VARYING(255) NOT NULL,
    "PROCESSING_STARTED" TIMESTAMP,
    "SEQUENCE_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "SEQUENCE_INDEX" BIGINT NOT NULL
);
ALTER TABLE "DEAD_LETTER_ENTRY"
    ADD CONSTRAINT "CONSTRAINT_5" PRIMARY KEY ("DEAD_LETTER_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DEAD_LETTER_ENTRY;
CREATE INDEX "IDXE67WCX5FIQ9HL4Y4QKHLCJ9CG" ON "DEAD_LETTER_ENTRY" ("PROCESSING_GROUP" NULLS FIRST);
CREATE INDEX "IDXRWUCPGS6SN93LDGOEH2Q9K6BN" ON "DEAD_LETTER_ENTRY" ("PROCESSING_GROUP" NULLS FIRST, "SEQUENCE_IDENTIFIER" NULLS FIRST);

CREATE
MEMORY
TABLE "DOMAIN_EVENT_ENTRY"
(
    "GLOBAL_INDEX" BIGINT NOT NULL,
    "EVENT_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "META_DATA" BINARY LARGE OBJECT,
    "PAYLOAD" BINARY LARGE OBJECT NOT NULL,
    "PAYLOAD_REVISION" CHARACTER VARYING(255),
    "PAYLOAD_TYPE" CHARACTER VARYING(255) NOT NULL,
    "TIME_STAMP" CHARACTER VARYING(255) NOT NULL,
    "AGGREGATE_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "SEQUENCE_NUMBER" BIGINT NOT NULL,
    "TYPE" CHARACTER VARYING(255)
);
ALTER TABLE "DOMAIN_EVENT_ENTRY"
    ADD CONSTRAINT "CONSTRAINT_8" PRIMARY KEY ("GLOBAL_INDEX");


CREATE
MEMORY
TABLE "SNAPSHOT_EVENT_ENTRY"
(
    "AGGREGATE_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "SEQUENCE_NUMBER" BIGINT NOT NULL,
    "TYPE" CHARACTER VARYING(255) NOT NULL,
    "EVENT_IDENTIFIER" CHARACTER VARYING(255) NOT NULL,
    "META_DATA" BINARY LARGE OBJECT,
    "PAYLOAD" BINARY LARGE OBJECT NOT NULL,
    "PAYLOAD_REVISION" CHARACTER VARYING(255),
    "PAYLOAD_TYPE" CHARACTER VARYING(255) NOT NULL,
    "TIME_STAMP" CHARACTER VARYING(255) NOT NULL
);
ALTER TABLE "SNAPSHOT_EVENT_ENTRY"
    ADD CONSTRAINT "CONSTRAINT_E" PRIMARY KEY ("AGGREGATE_IDENTIFIER", "SEQUENCE_NUMBER", "TYPE");
