CREATE SEQUENCE "HIBERNATE_SEQUENCE" START WITH 1;
CREATE MEMORY TABLE "ASSOCIATION_VALUE_ENTRY"(
    "ID" BIGINT NOT NULL,
    "ASSOCIATION_KEY" VARCHAR(255) NOT NULL,
    "ASSOCIATION_VALUE" VARCHAR(255),
    "SAGA_ID" VARCHAR(255) NOT NULL,
    "SAGA_TYPE" VARCHAR(255)
);
ALTER TABLE "ASSOCIATION_VALUE_ENTRY" ADD CONSTRAINT "CONSTRAINT_B" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSOCIATION_VALUE_ENTRY;
CREATE INDEX "IDXK45EQNXKGD8HPDN6XIXN8SGFT" ON "ASSOCIATION_VALUE_ENTRY"("SAGA_TYPE", "ASSOCIATION_KEY", "ASSOCIATION_VALUE");
CREATE INDEX "IDXGV5K1V2MH6FRXUY5C0HGBAU94" ON "ASSOCIATION_VALUE_ENTRY"("SAGA_ID", "SAGA_TYPE");
CREATE MEMORY TABLE "MENU_ENTITY"(
    "ID" VARCHAR(255) NOT NULL,
    "ACTIVE" BOOLEAN NOT NULL,
    "MENU_VERSION" INTEGER NOT NULL,
    "RESTAURANT_ID" VARCHAR(255)
);
ALTER TABLE "MENU_ENTITY" ADD CONSTRAINT "CONSTRAINT_6" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENU_ENTITY;
CREATE MEMORY TABLE "MENU_ENTITY_MENU_ITEMS"(
    "MENU_ENTITY_ID" VARCHAR(255) NOT NULL,
    "MENU_ID" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PRICE" DECIMAL(19, 2)
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENU_ENTITY_MENU_ITEMS;
CREATE MEMORY TABLE "RESTAURANT_ENTITY"(
    "ID" VARCHAR(255) NOT NULL,
    "AGGREGATE_VERSION" BIGINT NOT NULL,
    "NAME" VARCHAR(255)
);
ALTER TABLE "RESTAURANT_ENTITY" ADD CONSTRAINT "CONSTRAINT_1" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESTAURANT_ENTITY;
CREATE MEMORY TABLE "RESTAURANT_ENTITY_MENU_ITEMS"(
    "RESTAURANT_ENTITY_ID" VARCHAR(255) NOT NULL,
    "MENU_ID" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PRICE" DECIMAL(19, 2)
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESTAURANT_ENTITY_MENU_ITEMS;
CREATE MEMORY TABLE "RESTAURANTORDER_ENTITY"(
    "ID" VARCHAR(255) NOT NULL,
    "AGGREGATE_VERSION" BIGINT NOT NULL,
    "CUSTOMER" VARCHAR(255),
    "RESTAURANT_ID" VARCHAR(255),
    "STATE" VARCHAR(255)
);
ALTER TABLE "RESTAURANTORDER_ENTITY" ADD CONSTRAINT "CONSTRAINT_3" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESTAURANTORDER_ENTITY;
CREATE MEMORY TABLE "RESTAURANTORDER_ENTITY_LINE_ITEMS"(
    "RESTAURANTORDER_ENTITY_ID" VARCHAR(255) NOT NULL,
    "MENU_ID" VARCHAR(255),
    "NAME" VARCHAR(255),
    "QUANTITY" INTEGER NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESTAURANTORDER_ENTITY_LINE_ITEMS;
CREATE MEMORY TABLE "SAGA_ENTRY"(
    "SAGA_ID" VARCHAR(255) NOT NULL,
    "REVISION" VARCHAR(255),
    "SAGA_TYPE" VARCHAR(255),
    "SERIALIZED_SAGA" BLOB
);
ALTER TABLE "SAGA_ENTRY" ADD CONSTRAINT "CONSTRAINT_BD" PRIMARY KEY("SAGA_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SAGA_ENTRY;
CREATE MEMORY TABLE "TOKEN_ENTRY"(
    "PROCESSOR_NAME" VARCHAR(255) NOT NULL,
    "SEGMENT" INTEGER NOT NULL,
    "OWNER" VARCHAR(255),
    "TIMESTAMP" VARCHAR(255) NOT NULL,
    "TOKEN" BLOB,
    "TOKEN_TYPE" VARCHAR(255)
);
ALTER TABLE "TOKEN_ENTRY" ADD CONSTRAINT "CONSTRAINT_7" PRIMARY KEY("PROCESSOR_NAME", "SEGMENT");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TOKEN_ENTRY;
ALTER TABLE "RESTAURANT_ENTITY_MENU_ITEMS" ADD CONSTRAINT "FKTFXMWMSRE3LV2H8OT29YQ510N" FOREIGN KEY("RESTAURANT_ENTITY_ID") REFERENCES "RESTAURANT_ENTITY"("ID") NOCHECK;
ALTER TABLE "MENU_ENTITY_MENU_ITEMS" ADD CONSTRAINT "FKH3K81M5EJHJ6QHEDY1K3QAYTK" FOREIGN KEY("MENU_ENTITY_ID") REFERENCES "MENU_ENTITY"("ID") NOCHECK;
ALTER TABLE "RESTAURANTORDER_ENTITY_LINE_ITEMS" ADD CONSTRAINT "FKHL5IB1APFX55H61JE9SQIPFGD" FOREIGN KEY("RESTAURANTORDER_ENTITY_ID") REFERENCES "RESTAURANTORDER_ENTITY"("ID") NOCHECK;
