name: CI with Maven - Test, Build and Publish
# Trigger the workflow on push,
# but only for the main branch
on:
  push:
    branches: [ main ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Test, Build and Deploy with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./mvnw --batch-mode clean deploy -DskipIntegrationTests=false

      - name: Build and Publish container image by Maven (Jib)
        env:
          CONTAINER_IMAGE: docker.pkg.github.com/fraktalio/restaurant-demo/restaurant
        run: |
          ./mvnw --batch-mode jib:build -DskipTests \
              -Djib.to.image=$CONTAINER_IMAGE \
              -Djib.to.version=latest \
              -Djib.to.auth.username=${{ github.actor }} \
              -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
